name: Test the action
on: push

jobs:
  prettier_test:
    name: Test the plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Testing the action
        uses: ./
