name: Test the action on pull_request, no fetch-depth
on:
  - pull_request

jobs:
  prettier_test:
    name: Prettier job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Testing the action
        uses: ./
        with:
          main-branch: master
