name: Test the action on push, fetch-depth 2
on:
  - push

jobs:
  prettier_test:
    name: Prettier job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Testing the action
        uses: ./
        with:
          main-branch: master
